### ISSUE TITLE
Share popover button icon inconsistent with Calcite Components

### ISSUE THREAD

**Issue by bcree11** [Esri/instant-apps-components#11]
Calcite uses `scale="s"` for all calcite-icons no matter the scale of the parent component. To be consistent with them the popover button's icon should be updated to `scale="s"`

Example:
<img width="508" alt="image" src="https://user-images.githubusercontent.com/45497237/167916753-8e45b8fa-921a-4b05-9d46-8dd48b120ab1.png">

**Comment by rslibed** [comment]
Installed. Updates available on 10.2-release branch

**Comment by rslibed** [comment]
@bcree11 is this good to be verified/closed?

**Comment by kellyhutchins** [comment]
Looked at this one and seems like they are all scale="m" now
