### ISSUE TITLE
Enhancement requests for instant-app-measurement

### ISSUE THREAD

**Issue by Csmith246** [Esri/instant-apps-components#146]
A couple of Enhancement requests:

1. Color whichever tool is currently "Active", similar to this:
![image](https://github.com/Esri/instant-apps-components/assets/22039422/900c0dca-a379-4aaa-a82e-502099aff6e2)

2. Expose the references to the Measurement widgets and the coordinates widgets on the web component, so the developer can do things like: 
- clean up the graphics from a measure if the entire web component itself is destroyed (without first clicking the trash). The current behavior here is that the Measure graphic gets stuck on the display
![instant-app-measure-bug](https://github.com/Esri/instant-apps-components/assets/22039422/91c25752-fec8-4693-b44f-19cbe068b765)

- start a measure operation as soon as the tool is opened (without the user having to click a button to choose). Currently this isn't possible, since the developer doesn't have access to the internal Measurement widgets on the web component

**Comment by kellyhutchins** [comment]
@Csmith246  ok i'll look at these this afternoon.

**Comment by kellyhutchins** [comment]
@Csmith246  do you need access to the tools or is it enough for me to update so the widget destroys properly and also provide a way to set the active tool?

**Comment by kellyhutchins** [comment]
Also do you know if they have the hex values for the highlight color and if it is the same in light/dark themes?

**Comment by Csmith246** [comment]
https://github.com/Esri/instant-apps-components/pull/148 - Working on verification for Patch A.

Thanks again Kelly!

**Comment by kellyhutchins** [comment]
@Csmith246  is there anything else I need to add for measure? Or can i close this one out?

**Comment by Csmith246** [comment]
Everything is looking good. Thank you!
