### ISSUE TITLE
Share component - need update name and logo for "Twitter"?

### ISSUE THREAD

**Issue by avezina** [Esri/instant-apps-components#200]
Need to evaluate if we should reflect the "new name" and logo for Twitter in the Share component?

Examples:
- Implemented by the StoryMaps team https://devtopia.esri.com/WebGIS/arcgis-storymaps-mobile-android/issues/729#issuecomment-4260276
![image](https://github.com/Esri/instant-apps-components/assets/50338557/2329848d-40ca-4664-914e-00340a148ed2)

The ArcGIS Solutions team is using this component in the ArcGIS Solutions Deployment app and wondering if this needs to be updated as well.
https://www.arcgis.com/apps/solutions/index.html?gallery=true&solution=40eb887686a74d1b85647fdfb1b60c07&sortField=relevance&sortOrder=desc#home
![image](https://github.com/Esri/instant-apps-components/assets/50338557/c15d3030-a4c2-408f-ad0c-66e1080b4a62)

cc @Csmith246 @rslibed @MikeTschudi

**Comment by rslibed** [comment]
Yep - the social share component's Twitter options should reflect the current name and logo. We'll take a look at this

**Comment by rslibed** [comment]
Installed. Ready to test @ `1.0.0-beta.122`.

**Comment by avezina** [comment]
@MikeTschudi We should make sure to pull in this update for the Solutions Deployment app.

**Comment by avezina** [comment]
Looks like this is to be reverted
![image](https://github.com/Esri/instant-apps-components/assets/50338557/a8dc74a4-382e-45c6-962e-e8b85c453926)

**Comment by chris-fox** [comment]
Has the guidance on this changed? I see that the esri.com footer is now showing the X logo, but the tooltip still says Twitter.

![image](https://github.com/Esri/instant-apps-components/assets/6796763/d3a5a080-61fd-4fa6-a652-56dafd5fb2f8)

**Comment by MikeTschudi** [comment]
I just sent an email to socialcomm@esri.com to ask.

**Comment by rslibed** [comment]
@MikeTschudi Yep, I'll get this updated

**Comment by MikeTschudi** [comment]
Thank you!

**Comment by rslibed** [comment]
> Thank you!

Updated Twitter in social share back to X

**Comment by rslibed** [comment]
@kellyhutchins can you help verify this one?

**Comment by kellyhutchins** [comment]
Looks good in Nearby and Lookup
