### ISSUE TITLE
Enhancement: Add slot to splash modal content area 

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/instant-apps-components#277]
Some instant apps have an additional button added to the content area. For example, in the nearby app a "Find my location" button can be enabled via app config. 

Can we add a slot to the content area where devs can add a custom button.

**Comment by rslibed** [comment]
installed, ready to test at latest version

**Comment by kellyhutchins** [comment]
Looks good. Verified in Nearby and Lookup
