### ISSUE TITLE
ENH - Provide Embed options in the runtime share component

### ISSUE THREAD

**Issue by avezina** [Esri/instant-apps-components#32]
Would it be possible to provide Embed options in the runtime share component?  I believe this would be similar to what's exposed in the configuration share? 
![image](https://user-images.githubusercontent.com/50338557/190215644-cb2dc60a-6415-4440-828d-cb416b46b515.png)

App example where this is needed: https://arcg.is/Grn0O | Clinics Viewer Instant App built by Pat Dolan for Veteran Populations with ALS

Currently, the workaround would be the provide the embed code in the details of the app, which is not preferred.
![image](https://user-images.githubusercontent.com/50338557/190214818-f8723411-2f76-48e1-b09e-c0e5caeb63d4.png)

**Comment by rslibed** [comment]
@avezina my apologies, looks like this issue was missed. This is currently possible with the social-share web component's `embed` property. This would need to be updated on the app side. Logging an issue in the templates devtopia repo. Closing.
