### ISSUE TITLE
Expose a css variable to allow styling of the share button 

### ISSUE THREAD

**Issue by kellyhutchins** [Esri/instant-apps-components#9]
![Screen Shot 2022-04-20 at 3 24 41 PM](https://user-images.githubusercontent.com/2124187/164334884-93bf80f0-3d8f-4973-893d-e540d20de897.png)

Currently the only way I've been able to specify a custom color for the share button is to set the calcite icon variable value. But this also sets the color for the copy link icon. So it'd be great if we could get a css variable exposed that allows us control over the share button color. This is mostly necessary when its used in headings.

**Comment by rslibed** [comment]
Installed updates to 10.2 dev branch for testing.

**Comment by rslibed** [comment]
@kellyhutchins is this good to be verified/closed?

**Comment by kellyhutchins** [comment]
Looks good thanks.
